services:
  - type: web
    name: chess-api
    env: python
    buildCommand: "apt-get update && apt-get install -y stockfish && pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "8000"
      - key: STOCKFISH_PATH
        value: "/usr/bin/stockfish"
